# Generated by Django 5.2.6 on 2025-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tariff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarifflimit",
            name="code",
            field=models.CharField(
                choices=[
                    ("all", "all"),
                    ("wb", "Wildberries"),
                    ("ozon", "Ozon"),
                    ("yandex_market", "Яндекс Маркет"),
                    ("aliexpress", "AliExpress"),
                ],
                default="all",
                max_length=50,
                unique=True,
                verbose_name="Код маркетплейса",
            ),
        ),
    ]
