# Generated by Django 5.2.6 on 2025-10-27 14:41

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tariff", "0003_add_initial_tariffs"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tariff",
            field=models.ForeignKey(
                default=users.models._get_tariff_default,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="tariff.tariff",
                verbose_name="Тариф",
            ),
        ),
    ]
