FROM python:3.12-slim

# Устанавливаем зависимости для poetry
RUN apt-get update && apt-get install -y curl build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

# Устанавливаем poetry
RUN pip install poetry==1.8.3
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY pyproject.toml poetry.lock* ./
COPY saas/ ./saas/

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --only saas,shared

WORKDIR /app/saas
