# generated by datamodel-codegen:
#   filename:  http://0.0.0.0:8088/api/schema/
#   timestamp: 2025-10-28T14:52:53+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class User(BaseModel):
    id: int
    telegram_id: int
    telegram_username: str = Field(..., title="Telegram ник")
    tariff: int = Field(..., title="Тариф")
    date_joined: datetime


class UserCreate(BaseModel):
    telegram_id: int
    telegram_username: Optional[str] = None
    tariff: int = Field(..., title="Тариф")


class UserCreateRequest(BaseModel):
    telegram_id: int
    telegram_username: Optional[str] = None
