# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import Optional

from pydantic import AwareDatetime, BaseModel, Field


class CodeEnum(Enum):
    FREE = "free"
    BASIC = "basic"
    PREMIUM = "premium"


class Tariff(BaseModel):
    id: int
    code: CodeEnum
    name: str
    price: Decimal = Field(..., title="Цена в месяц (руб)")
    description: str = Field(..., title="Описание")


class TariffRequest(BaseModel):
    code: CodeEnum


class User(BaseModel):
    telegram_id: int
    telegram_username: str = Field(..., title="Telegram ник")
    tariff: Tariff
    date_joined: AwareDatetime


class UserCreate(BaseModel):
    telegram_id: int
    telegram_username: Optional[str] = None
